default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qna_rails_development

test:
  <<: *default
  database: qna_rails_test

production:
  <<: *default
  database: qna_rails_production
  username: qna_rails
  password: <%= ENV['QNA_RAILS_DATABASE_PASSWORD'] %>
